[package]
name = "wastebin"
version = "2.4.2"
edition = "2021"
rust-version = "1.70"

[dependencies]
askama = { version = "0.12", default-features = false, features = ["with-axum"] }
askama_axum = { version = "0.3" }
async-compression = { version = "0.4", features = ["tokio", "zstd"] }
axum = { version = "0.6", features = ["headers", "json", "query"] }
axum-extra = { version = "0", features = ["cookie-signed"] }
bytes = "1"
chacha20poly1305 = "0.10.1"
hex = "0"
http-body = "0"
lru = "0"
mime = "0"
qrcodegen = "1"
rand = "0"
rusqlite = { version = "0.28", features = ["bundled"] }
rusqlite_migration = { git = "https://github.com/cljoly/rusqlite_migration", rev = "dff7b6ba305d0d5b334c40fde72a88e28984242a" }
rust-argon2 = "2.0.0"
sha2 = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syntect = { version = "5", default-features = false, features = ["html", "plist-load", "regex-fancy"] }
thiserror = "1"
time = { version = "0.3", features = ["macros", "serde"] }
tokio = { version = "1", features = ["full"] }
tower = { version = "0", default-features = false }
tower-http = { version = "0", features = ["compression-full", "limit", "timeout", "trace"] }
tracing = "0"
tracing-subscriber = "0"
url = "2"
zstd = "0.12"

[dev-dependencies]
http = "0"
hyper = { version = "0", features = ["server", "tcp", "stream"] }
reqwest = { version = "0", default-features = false, features = ["cookies", "json"] }
tower = { version = "0", default-features = false, features = ["util", "make"] }
tower-service = "0"

[profile.release]
strip = "debuginfo"
lto = "fat"
